### ISSUE TITLE
Architectural Curiosity of the Project

### ISSUE THREAD

**Issue by jiwon79** [CoconutGoodie/figma-plugin-react-vite#4]
### Base Idea
- `plugin.ts` depend on `@plugin` and `@common`.
- `index.html` depend on `@ui` and `@common`.
- `@common` don't depend on `@plugin` and `@ui`.
- interact with figma code depend on `plugin.ts` not `index.html`, 

### Current Situation
- `./src/common/network/messages/CreateRectMessage.ts`
  - It create rect to interact with figma.
  - It should only related on `plugin.ts`. However `plugin.ts`, `index.html` are depend on it.(`@common` include CreateRectMessage.ts)
  - I think it is something wrong.
- If you created a `CreateRectAction.ts`(function that create rect to interact figma) under the `@plugin`.
  - Message object must be created in `@common` to send in UI
  - Message object, handle function include logic.
  - handle function depend on `CreateRectAction.ts`, `@plugin`
  - Then, `@common` depend on `@plugin`.
 - If `CreateRectAction.ts` is under `@common`
   - It is wrong architectural because `CreateRectAction.ts` is interact with figma.

### Curiosity
How can I add interact figma code without depend on `@ui`? Could you please let me know if I'm not familiar with how to use the `monorepo-networker` library?

**Comment by iGoodie** [comment]
Hey there! 😁 

Thanks for the great question/architectural issue you brought to the table 🎉

## Comments on your cases
I think you have valid points, which makes the architecture a bit hard to extend. 😀 
Let me try to give my comment on each situation you wrote down:
1. *Every message is under `@common/network/messages`*. This was an idea heavily inspired by how Minecraft Forge's netcode works. Both sides can access it; one side uses it to be able to dispatch a "message sending" action, other side uses it to actually accommodate incoming "message" and handle it in some way. So handler in this case creates a two-way dependency on `@common` and any other side. I find your word valuable on this.
2. *Message depending on a utility/code specific to a side*. This one a very good *eye-opener* for me. As I never considered in `monorepo-networker` there might be 2 completely isolated sides. I always had commonly available sides were a matter of subject. You are so right with this one!
3. *Bringing in the handling code inside `@common`, even tho it's not a common code*. Absolute the worst architectural design we could ever do, so you're absolutely right with this one as well.

## What actions should be taken?
I think you made me see a crucial point of view, which I think Monorepo Networker should receive as a few updates:
- Message receive handlers are highly **side-dependent**. Therefore, they should be handled on their corresponding side. As you suggested ✅ 
- `@common/network` should only be there to;
	- *Define sides* - Which sides are available throughout the application ✅
	- *Define communication strategies* - Which strategy a certain side uses to communicate with another side ✅
	- *Define which messages are there* - Which messages are present for a certain side ✅

I'm actually going to create this as an issue in `monorepo-networker`, to accommodate this very fundamental architectural problem.

Thanks a lot for enlightening me,
Feel free to share your thoughts 😁

**Comment by jiwon79** [comment]
First of all, thank you so much for quick replying my question.

>`@common/netork` should only be there to;
> - Define sides
> - Define communication strategies
> - Define which message are there

I absolute agree this. After solve this issue at `monorepo-network`, I think it would be better to changes `@common/network/init.ts, sides.ts` with specific logic location.

Current, there are not only what kind of Side exist but how attach and listen message(`window.addEventListener("message", callback)`, `figma.ui.on("message", callback)`) in `@common`.

`@common/network` just define what kind of sides(UI, PLUGIN) there. Then, specific code that how attach and listen message are located in each package(`@ui`, `@plugin`).

What do you think about it?

**Comment by iGoodie** [comment]
Most welcome! It was very valuable to see you provide your vision on the DX 🎉 

I totally agree with it. I think a more extensible file system would be like so:

- `@common`
    - `sides.ts` ["Client", "Server", "UI"]
    - `messages.ts` ["createRect", "sayHello", "ping"]
- `@side`
    - `message-transmitters.ts` Strategy registrar on how to transmit message to other sides
    - `message-receivers.ts` Strategy registrar on how to receive/listen to message from other sides
    - `message-handlers.ts` Behavior registrar on how to handle incoming messages
    - `entry.ts` AppNetwork.initNetwork(AppNetwork.Sides.CLIENT, initTransmitters, initReceivers, initHandlers);
    - `feature.ts` AppNetwork.send(AppNetwork.Sides.UI, "createRect", { ... });
    
Not the actual implementation, but leaving `@common` with only the backbones and a summary of the whole network is

**Comment by iGoodie** [comment]
Here's the final API design I finally came up with.
What do you think @jiwon79 ? 😄 

```ts
// --------- @common/network/sides.ts

export const UI = new NetworkSide<{
  focusOnSelected(): void;
  focusOnElement(elementId: string): void;
}>("UI-side");

export const CLIENT = new NetworkSide<{
  getClientTime(): number;
  execute(script: string): void;
}>("Client-side");

export const SERVER = new NetworkSide<{
  getServerTime(): number;
  fetchUser(userId: string): { id: string; name: string };
  markPresence(online: boolean): void;
}>("Server-side");

// --------- @client/network/clientChannel.ts

export const CLIENT_CHANNEL = new NetworkHandler(CLIENT, {
  attachListener(next) {
    const listener = (event: MessageEvent) => {
      if (event.data?.pluginId == null) return;
      next(event.data.pluginMessage);
    };
    window.addEventListener("message", listener);
    return listener;
  },
  detachListener(listener) {
    window.removeEventListener("message", listener);
  },
});

CLIENT_CHANNEL.registerEmitStrategy(UI, (message) => {
  console.log("Sending to UI", message);
});

CLIENT_CHANNEL.registerEmitStrategy(SERVER, (message) => {
  parent.postMessage({ pluginMessage: message }, "*");
});

CLIENT_CHANNEL.registerMessageHandler("execute", (script) => {
  eval(script);
});

CLIENT_CHANNEL.registerMessageHandler("getClientTime", () => {
  return Date.now();
});

// --------- @client/main.ts

MonorepoNetworker.initialize(CLIENT, CLIENT_CHANNEL);

console.log("We're at", MonorepoNetworker.currentSide);

async function bootstrap() {
  CLIENT_CHANNEL.emit(SERVER, "markPresence", [true]);

  const user = await CLIENT_CHANNEL.request(SERVER, "fetchUser", ["USR-1"]);
  console.log(user.id);
  console.log(user.name);

  const serverTime = await CLIENT_CHANNEL.request(SERVER, "getServerTime", []);
  console.log(serverTime);
}

bootstrap();
```

**Comment by iGoodie** [comment]
With #12, I think everything we've been discussing here should be covered! 🎉 
Feel free to reopen the issue, if I'm missing anything 😄
